import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // for now it's including all translations,
  // as it grows it may be needed to send only
  // the relevant translations to the client-side.
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang={locale} className="relative h-full">
      <body className={inter.className + " h-full"}>
        <div className="absolute left-0 top-0 -z-10 flex h-full w-full flex-row">
          <div className="w-1/3 bg-blue-500" />
          <div className="w-1/3 bg-white" />
          <div className="w-1/3 bg-red-500" />
        </div>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
